require("vim-options")
require("basic_autocommands")
require("plugin-manager")
require("basic_keymaps")
require("statusline")
local start = vim.uv.hrtime()
require("languages")
print("Languages loaded: " .. (vim.uv.hrtime() - start) / 1000000 .. "ms")
